CREATE VIEW dem.strip_dem_all AS
select dem_id,
       stripdemid,
       pairname,
       sensor1,
       sensor2,
       catalogid1,
       catalogid2,
       cent_lat,
       cent_lon,
       geocell,
       region,
       epsg,
       proj4,
       nd_value,
       dem_res,
       algm_ver,
       s2s_ver,
       mask_dens,
       valid_dens,
       valid_area,
       valid_perc,
       water_area,
       water_perc,
       cloud_area,
       cloud_perc,
       avgconvang,
       avg_ht_acc,
       avg_sunel1,
       avg_sunel2,
       rmse,
       location,
       filesz_dem,
       filesz_mt,
       filesz_or,
       filesz_or2,
       wkb_geometry,
       acqdate1,
       acqdate2,
       avgacqtm1,
       avgacqtm2,
       is_lsf,
       is_xtrack,
       edgemask,
       watermask,
       cloudmask,
       cr_date,
       index_date,
       status
from dem.strip_dem_staging sds
UNION ALL
select dem_id,
       stripdemid,
       pairname,
       sensor1,
       sensor2,
       catalogid1,
       catalogid2,
       cent_lat,
       cent_lon,
       geocell,
       region,
       epsg,
       proj4,
       nd_value,
       dem_res,
       algm_ver,
       s2s_ver,
       mask_dens,
       valid_dens,
       valid_area,
       valid_perc,
       water_area,
       water_perc,
       cloud_area,
       cloud_perc,
       avgconvang,
       avg_ht_acc,
       avg_sunel1,
       avg_sunel2,
       rmse,
       location,
       filesz_dem,
       filesz_mt,
       filesz_or,
       filesz_or2,
       wkb_geometry,
       acqdate1,
       acqdate2,
       avgacqtm1,
       avgacqtm2,
       is_lsf,
       is_xtrack,
       edgemask,
       watermask,
       cloudmask,
       cr_date,
       index_date,
       'tape'
from dem.strip_dem sd
where not exists (select 1
                  from dem.strip_dem_staging sds
                  where sds.dem_id = sd.dem_id and sds.stripdemid = sd.stripdemid);

comment on view dem.strip_dem_all is 'Concatenation of strip DEM source tables. Strip DEMs on tape that are also on vida (strip_dem_staging) are excluded.';

alter view dem.strip_dem_all owner to pgc_gis_admin;

grant select on dem.strip_dem_all to pgc_users;
